import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // Tạm tắt để build Docker không lỗi
import { Toaster } from "sonner";
import { ToastProvider } from "@/components/ui/ToastContext";
import "./globals.css";

// Sử dụng font hệ thống để tránh lỗi tải font khi build Docker
const geistSansVariable = "--font-geist-sans";
const geistMonoVariable = "--font-geist-mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Thêm suppressHydrationWarning vào đây
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSansVariable} ${geistMonoVariable} antialiased font-sans`}
        suppressHydrationWarning // Thêm vào đây nữa để chắc chắn
      >
        <ToastProvider>
          {children}
          <Toaster position="top-center" richColors />
        </ToastProvider>
      </body>
    </html>
  );
}