sonar.organization=lghthien
sonar.projectKey=Lghthien_library-website-microservice

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=library-website-microservice
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" with "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude directories
sonar.exclusions=**/node_modules/**, **/dist/**, **/.next/**, **/coverage/**, **/test/**, **/*.spec.ts, **/*.test.ts, **/*.js

# JavaScript/TypeScript configurations
sonar.javascript.environments=node, browser
sonar.typescript.tsconfigPath=**/tsconfig.json
